// This file has been automatically generated by strace2c.
// Do not edit it!

#include "common/op_types.h"

trace_op_t trace_ops[] = {
    /* #10 = 0xa */ { .opcode = SELECT_OP, .args.select = { 1 } },
    /* here should probably be a waituntil because of the accept4 call */
    /* #11 = 0xb */ /*{ .opcode = SELECT_OP, .args.select = { 99881 } },*/
    /* #12 = 0xc */ { .opcode = RECVFROM_OP, .args.recvfrom = { 87, 3, "GET /index.html HTTP/1.0\r\nHost: localhost\r\nUser-Agent: ApacheBench/2.3\r\nAccept: */*\r\n\r\n", 1024, 0, NULL, NULL } },
    /* #13 = 0xd */ { .opcode = OPEN_OP, .args.open = { 8, "/www/index.html", O_RDONLY|O_NONBLOCK, 0 } },
    /* #14 = 0xe */ { .opcode = FSTAT_OP, .args.fstat = { 0, 8 } },
    /* #15 = 0xf */ { .opcode = WRITEV_OP, .args.writev = { 236, 3, .iovec = { "HTTP/1.1 200 OK\r\nServer: nginx/1.12.1\r\nDate: Sun, 01 Jan 2012 00:04:34 GMT\r\nContent-Type: text/html\r\nContent-Length: 38119\r\nLast-Modified: Thu, 26 Apr 2018 06:02:24 GMT\r\nConnection: close\r\nETag: \"5ae16b70-94e7\"\r\nAccept-Ranges: bytes\r\n\r\n" , 236 }, 1 } },
    /* #16 = 0x10 */ { .opcode = MODSENDFILE_OP, .args.sendfile = { 18201, 3, 8, NULL, 18201} },
    /* #17 = 0x11 */ { .opcode = WRITE_OP, .args.write = { 106, 5, 106, 1 } }, /* that is the write to the logfile, open it before */
    /* #18 = 0x12 */ { .opcode = CLOSE_OP, .args.close = { 0, 8 } },
    /* #19 = 0x13 */ /*{ .opcode = CLOSE_OP, .args.close = { 0, 3 } },*/
    { .opcode = INVALID_OP },
    /* This is the log file which should be open before handling requests */
    { .opcode = OPEN_OP, .args.open = { 5, "/tmp/nginx_access.log", O_WRONLY|O_CREAT|O_APPEND, 0 } },
};