// This file has been automatically generated by strace2c.
// Do not edit it!

#include "common/op_types.h"

trace_op_t trace_ops[] = {
    /* #1 = 0x1 */ { .opcode = WAITUNTIL_OP, .args.waituntil = { 0, 113610 } },
    /* #2 = 0x2 */ { .opcode = OPEN_OP, .args.open = { 3, "/test.tar", O_RDONLY|O_LARGEFILE, 0 } },
    /* #3 = 0x3 */ { .opcode = WAITUNTIL_OP, .args.waituntil = { 0, 19090 } },
    /* #4 = 0x4 */ { .opcode = READ_OP, .args.read = { 512, 3, 512, 1 } },
    /* #5 = 0x5 */ { .opcode = WAITUNTIL_OP, .args.waituntil = { 0, 24439 } },
    /* #6 = 0x6 */ { .opcode = UNLINK_OP, .args.unlink = { -1, "128.bin" } },
    /* #7 = 0x7 */ { .opcode = OPEN_OP, .args.open = { 4, "128.bin", O_WRONLY|O_CREAT|O_EXCL|O_LARGEFILE, 0100644 } },
    /* #8 = 0x8 */ { .opcode = WAITUNTIL_OP, .args.waituntil = { 0, 2498 } },
    /* #9 = 0x9 */ { .opcode = SENDFILE_OP, .args.sendfile = { 131072, 4, 3, NULL, 131072 } },
    /* #10 = 0xa */ { .opcode = WAITUNTIL_OP, .args.waituntil = { 0, 3486 } },
    /* #11 = 0xb */ { .opcode = CLOSE_OP, .args.close = { 0, 4 } },
    /* #12 = 0xc */ { .opcode = WAITUNTIL_OP, .args.waituntil = { 0, 24883 } },
    /* #13 = 0xd */ { .opcode = READ_OP, .args.read = { 512, 3, 512, 1 } },
    /* #14 = 0xe */ { .opcode = WAITUNTIL_OP, .args.waituntil = { 0, 12020 } },
    /* #15 = 0xf */ { .opcode = UNLINK_OP, .args.unlink = { -1, "256.bin" } },
    /* #16 = 0x10 */ { .opcode = OPEN_OP, .args.open = { 4, "256.bin", O_WRONLY|O_CREAT|O_EXCL|O_LARGEFILE, 0100644 } },
    /* #17 = 0x11 */ { .opcode = SENDFILE_OP, .args.sendfile = { 262144, 4, 3, NULL, 262144 } },
    /* #18 = 0x12 */ { .opcode = WAITUNTIL_OP, .args.waituntil = { 0, 1187 } },
    /* #19 = 0x13 */ { .opcode = CLOSE_OP, .args.close = { 0, 4 } },
    /* #20 = 0x14 */ { .opcode = WAITUNTIL_OP, .args.waituntil = { 0, 14204 } },
    /* #21 = 0x15 */ { .opcode = READ_OP, .args.read = { 512, 3, 512, 1 } },
    /* #22 = 0x16 */ { .opcode = WAITUNTIL_OP, .args.waituntil = { 0, 11720 } },
    /* #23 = 0x17 */ { .opcode = UNLINK_OP, .args.unlink = { -1, "512.bin" } },
    /* #24 = 0x18 */ { .opcode = OPEN_OP, .args.open = { 4, "512.bin", O_WRONLY|O_CREAT|O_EXCL|O_LARGEFILE, 0100644 } },
    /* #25 = 0x19 */ { .opcode = SENDFILE_OP, .args.sendfile = { 524288, 4, 3, NULL, 524288 } },
    /* #26 = 0x1a */ { .opcode = WAITUNTIL_OP, .args.waituntil = { 0, 1186 } },
    /* #27 = 0x1b */ { .opcode = CLOSE_OP, .args.close = { 0, 4 } },
    /* #28 = 0x1c */ { .opcode = WAITUNTIL_OP, .args.waituntil = { 0, 14335 } },
    /* #29 = 0x1d */ { .opcode = READ_OP, .args.read = { 512, 3, 512, 5 } },
    /* #30 = 0x1e */ { .opcode = READ_OP, .args.read = { 0, 3, 512, 1 } },
    /* #31 = 0x1f */ { .opcode = WAITUNTIL_OP, .args.waituntil = { 0, 2682 } },
    /* #32 = 0x20 */ { .opcode = CLOSE_OP, .args.close = { 0, 3 } },
    { .opcode = INVALID_OP } 
};
