// This file has been automatically generated by strace2c.
// Do not edit it!

#include "common/op_types.h"

trace_op_t trace_ops[] = {
    /* #65 = 0x41 */ { .opcode = SELECT_OP, .args.select = { 99940 } },
    /* #66 = 0x42 */ { .opcode = WAITUNTIL_OP, .args.waituntil = { 0, 7745 } },
    /* #67 = 0x43 */ { .opcode = RECVFROM_OP, .args.recvfrom = { 87, 3, "GET /index.html HTTP/1.0\r\nHost: localhost\r\nUser-Agent: ApacheBench/2.3\r\nAccept: */*\r\n\r\n", 1024, 0, NULL, NULL } },
    /* #68 = 0x44 */ { .opcode = WAITUNTIL_OP, .args.waituntil = { 0, 46281 } },
    /* #69 = 0x45 */ { .opcode = OPEN_OP, .args.open = { 8, "/www/index.html", O_RDONLY|O_NONBLOCK, 0 } },
    /* #70 = 0x46 */ { .opcode = WAITUNTIL_OP, .args.waituntil = { 0, 1157 } },
    /* #71 = 0x47 */ { .opcode = FSTAT_OP, .args.fstat = { 0, 8 } },
    /* #72 = 0x48 */ { .opcode = WAITUNTIL_OP, .args.waituntil = { 0, 33518 } },
    /* #73 = 0x49 */ { .opcode = WRITEV_OP, .args.writev = { 236, 3, .iovec = { "HTTP/1.1 200 OK\r\nServer: nginx/1.12.1\r\nDate: Sun, 01 Jan 2012 00:03:58 GMT\r\nContent-Type: text/html\r\nContent-Length: 18201\r\nLast-Modified: Wed, 02 May 2018 06:29:37 GMT\r\nConnection: close\r\nETag: \"5ae95ad1-4719\"\r\nAccept-Ranges: bytes\r\n\r\n" , 236 }, 1 } },
    /* #74 = 0x4a */ { .opcode = WAITUNTIL_OP, .args.waituntil = { 0, 2066 } },
    /* #75 = 0x4b */ { .opcode = MODSENDFILE_OP, .args.sendfile = { 18201, 3, 8, NULL, 18201 } },
    /* #76 = 0x4c */ { .opcode = WAITUNTIL_OP, .args.waituntil = { 0, 21915 } },
    /* #77 = 0x4d */ { .opcode = WRITE_OP, .args.write = { 106, 5, 106, 1 } },
    /* #78 = 0x4e */ { .opcode = WAITUNTIL_OP, .args.waituntil = { 0, 1432 } },
    /* #79 = 0x4f */ { .opcode = CLOSE_OP, .args.close = { 0, 8 } },
    /* #80 = 0x50 */ { .opcode = WAITUNTIL_OP, .args.waituntil = { 0, 8867 } },
    { .opcode = INVALID_OP },
    /* This is the log file which should be open before handling requests */
    { .opcode = OPEN_OP, .args.open = { 5, "/tmp/nginx_access.log", O_WRONLY|O_CREAT|O_APPEND, 0 } },
};
